主题:
  主窗口大小:
    宽度: 800
    高度: 800
  主菜单按钮文字大小:
    AI: 30
    建议: 18
    整理: 18
    设置: 18
  分割线颜色: null
  圆角半径: 40
  字体: HarmonyOS Sans SC
  数字6标识:
    字体颜色: 255, 255, 255
    描边宽度: 6
    描边颜色: 72, 143, 224
    背景颜色: 42, 130, 228
动效:
  主菜单:
    展开时间: 500
    收起时间: 500
