主题:
  主窗口大小:
  - 800
  - 800
  主菜单按钮文字大小:
    AI: 30
    建议: 18
    整理: 18
    设置: 18
  圆角半径: 40
  字体: HarmonyOS Sans SC
  数字6标识:
    字体颜色: 255, 255, 255
    描边宽度: 6
    描边颜色: 72, 143, 224
    背景颜色: 42, 130, 228
  整理:
    分割线长度:
      分割线1: 70
      分割线2: 160
    坐标:
      分割线1: 18, 50
      分割线2: 18, 107
      开始整理: 18, 50
      整理历史记录: 18, 110
      标题: 18, 8
    描边颜色: 72, 143, 224
    窗口大小:
    - 270
    - 250
    背景颜色: 42, 130, 228
  设置:
    勾选框:
      描边颜色: 131,183,242
      未选中: 212, 230, 250
      选中: 94, 185, 255
      鼠标悬停: 197, 233, 255
    描边颜色: 72, 143, 224
    窗口大小:
    - 504
    - 400
    背景颜色: 42, 130, 228
    选项卡:
      分割线半宽: 3
      字体颜色: 42, 130, 228
      背景颜色: 212, 230, 250
      被选中背景颜色: 246, 250, 254
      高度: 40
      鼠标悬停背景颜色: 204, 210, 217
动效:
  主菜单:
    展开时间: 500
    收起时间: 500
  整理:
    进入时间: 500
    退出时间: 500
  设置:
    进入时间: 500
    退出时间: 500
